# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 114d3fbdbb10c3f7e9b88e0cf4469996d3358f881e591cae472b31bb1a910d08483c7bfc5ed041b45e74dd62e06c737f66009ee7012fdbc621dca57937b061a5

test:
  secret_key_base: e871cf4340f084ccf8851270d04d96d8c03a91920a2c7befc84d7258565c2727d70436c58811ea28ad5ab90fff634f1c73d703ea59540be2509f5efd3695071c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
