# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8504db82a418e2eb434d9b64c1bd26a22db6dc206c036c9cd3aee3f56109f51c475b1662893d331b258be49528824ee5aa43f5eaa89cddda3c61f43a230cb17

test:
  secret_key_base: 02a9bc2935ea619742d7633a430a99490f424828a5e3b4e822e962fe43691bea03a44024c9a8aa2b309fe84a71c33f9cab8a336ddbb1ce5a1bd14e81b5d3e645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
